version: '3.8'

services:
  fastapi-app:
    build: .  # This should be a string pointing to the current directory
    ports:
      - "8000:8000"
    volumes:
      - ./app/data:/app/data
    restart: always

